{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "purchase_revenue", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{method=\"DELETE\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "purchase_sold", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu{__proxy_source__=\"influx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "purchase_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "user_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "auth_success", "legendFormat": "__auto" },
    { "expr": "auth_fail", "legendFormat": "__auto" }
   ]
  }
 ]
}